---
abstract: 'Text pipes that convert W3CDTF date-time strings and objects'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Pipe-W3CDTF
provides:
  Text::Pipe::W3CDTF:
    file: lib/Text/Pipe/W3CDTF.pm
    version: 1.100890
  Text::Pipe::W3CDTF::Format:
    file: lib/Text/Pipe/W3CDTF/Format.pm
    version: 1.100890
  Text::Pipe::W3CDTF::Parse:
    file: lib/Text/Pipe/W3CDTF/Parse.pm
    version: 1.100890
requires:
  Carp: 0
  DateTime::Format::W3CDTF: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  Text::Pipe: 0
  Text::Pipe::Base: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Pipe-W3CDTF
  homepage: http://search.cpan.org/dist/Text-Pipe-W3CDTF/
  repository: http://github.com/hanekomu/Text-Pipe-W3CDTF
version: 1.100890
